# .gitlab-ci.yml

stages:
  - build
  - test

before_script:
  - echo Global before

after_script:
  - echo Global after

build:
  stage: build
  script: echo Build!

test1:
  stage: test
  script: echo Test1!

test2:
  stage: test
  script: echo Test2!