# .gitlab-ci.yml

stages:
  - stage1
  - stage2
  - stage3


job1:
  stage: stage1
  script: echo hello

job2:
  stage: stage2
  script: 'false'
  allow_failure: true

job3:
  stage: stage3
  script: echo hello