# image: ondrejsika/ci

# stages:
#   - build

# build_js:
#   image: node
#   stage: build
#   variables:
#     GIT_CLEAN_FLAGS: -ffdx -e node_modules
#   script:
#     - yarn
#     - yarn static
#   artifacts:
#     paths:
#       - out/**/*

# build_docker:
#   stage: build
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker build . -t $CI_REGISTRY_IMAGE
#     - docker push $CI_REGISTRY_IMAGE


deploy:
  script: echo 'Deploy!'
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.dev.company.com