stages:
  - build

build_js:
  image: node
  stage: build
  script:
    - yarn
    - yarn static

build_docker:
  image: docker
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build . -t $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE